### ISSUE TITLE
Changement du port de l'instance 7878 > 8000

### ISSUE THREAD

**Issue by Wisou** [etalab/addok-docker#10]
Bonjour,

Nous souhaiterions pouvoir changer le port de l'instance.
J'ai testé en modifiant le fichier yml et en relançant les instances docker mais ça n'a pas suffit.
Pourriez-vous m'aider ?
Cordialement,

**Comment by sneycampos** [comment]
You need run docker-compose with --build, have you tried?

**Comment by Simon-LePennec** [comment]
Same issue here, I tried modifying yml file, docker-compose with build command line, but ...

```
simon@simon-VirtualBox:~/ban$ sudo docker-compose build
addok-redis uses an image, skipping
addok uses an image, skipping

```
