### ISSUE TITLE
Question: Le rechargement des données

### ISSUE THREAD

**Issue by loverg-c** [etalab/addok-docker#11]
Bonjour,

Si j'ai bien compris les données se chargent au lancement du container,
Même si la liste des adresses françaises ne changent pas toute les semaines, nous aimerions faire tourner un CRON pour les mettre à jour en cas de besoin

Du coup la meilleure solution serait de faire un script qui fait un `wget/unzip` des données et relance le container ? Ou alors est-ce que le redis recharge automatiquement le dump si on le modifie à chaud (et dans ce cas un simple cron sur le `wget/unzip` suffirait) ? 

Merci d'avance :)

**Comment by jdesboeufs** [comment]
Les adresses changent justement toutes les semaines, même si la diffusion est suspendue depuis novembre dernier.
La MAJ reprend la semaine prochaine.
Il faut relancer redis, le dump est lu au chargement.

**Comment by loverg-c** [comment]
Parfait merci ! :)
