### ISSUE TITLE
Usage du CPU par redis

### ISSUE THREAD

**Issue by loverg-c** [etalab/addok-docker#12]
Bonjour, 

Voici l'usage du cpu sous docker et mac après 1minutes de lancement (idem après 15minutes)

![Capture d’écran 2019-06-26 à 14 54 46](https://user-images.githubusercontent.com/4719382/60182159-07494e00-9824-11e9-83de-66729996c5a7.png)

On dirait que cela vient du container redis car si je coupe addok cela reste pareil, si je coupe redis cela chute d'un coup.

Y a t-il une configuration que l'on peut modifier pour descendre cet usage du cpu (j'ai déjà limité à 2cpu et 4gb de ram au niveeau de docker desktop) ? 

Merci d'avance !

**Comment by jdesboeufs** [comment]
Ce n'est pas normal.
En principe redis n'utilise qu'un seul CPU et l'utilisation retombe à zéro dès que le dump est chargé.
Nous utilisons ces conteneurs en production.

**Comment by jdesboeufs** [comment]
4 Go pour la base France entière c'est juste quand même. Je crois que de notre côté on consomme 6 Go par instance Redis.

**Comment by Laurent-Hervaud** [comment]
Je confirme il faut 6Go. Il y a des chances que le container Redis boucle sur le chargement des data ce qui pourrait expliquer la conso cpu

**Comment by loverg-c** [comment]
Je testerai sur ma configuration linux la semaine prochaine (car docker sur mac est connu pour avoir quelques soucis de performance d'accès aux fichiers) et je reviendrais vers vous !

En tout cas merci à vous ! :)

**Comment by jdesboeufs** [comment]
Sous Mac il faut penser à ça :
<img width="518" alt="Capture d’écran 2019-07-02 à 07 06 02" src="https://user-images.githubusercontent.com/1231232/60483935-e8b9db80-9c97-11e9-9a05-07200a5d2399.png">

**Comment by loverg-c** [comment]
Bonjour,

Cela va mieux sur linux (mon mac perso n'a que 8gb de ram, donc allouer 8gb de ram à docker n'est pas possible :/)

Je ferme le ticket, merci :)
