### ISSUE TITLE
Mise à jour des données

### ISSUE THREAD

**Issue by Vianney24** [etalab/addok-docker#16]
Bonjour, 

je voudrais savoir si les données sont mise à jour ? et si oui combien de fois par mois ou par semaine ?
Merci

**Comment by 2ec0b4** [comment]
Sur cette page, tu peux voir que les données sont mises à jour de manière hebdomadaire : https://adresse.data.gouv.fr/donnees-nationales

**Comment by jdesboeufs** [comment]
Oui MAJ hebdomadaire bien que pas encore 100% automatisée ;)
