### ISSUE TITLE
Update DB

### ISSUE THREAD

**Issue by Fabback** [etalab/addok-docker#17]
Bonjour,

D'abord merci pour cet outils ultra complet et simple a mettre en oeuvre, nous l'avons installé en interne suite à quelques problèmes d'accès à l'API adresse, nous utilisons du coup ce docker en source principale.
Ceci étant dit je vous pose non pas une "issue" mais plutôt une question : Y'a-t-il une procédure (ou un CRON) pour mettre à jour la base que nous hébergeons, ou devenons nous re-télécharger la base pré-indexée à chaque fois ?

Cordialement,

**Comment by jdesboeufs** [comment]
Actuellement il faut re-télécharger, et c'est ce que nous faisons en production.

Je ferme car c'est une vieille issue, n'hésitez pas à réouvrir.
