### ISSUE TITLE
Requirement : Au moins 6 Go de RAM disponible (à froid) for addok or redis ?

### ISSUE THREAD

**Issue by kopax** [etalab/addok-docker#20]
Hi, I want to start on mesos an addok service.

I need to allocate the RAM and CPU per services, so far there is two, addok and redis.

- Au moins 6 Go de RAM disponible (à froid)
- 8 Go d'espace disque disponible (hors logs)

How should I split those requirements between the two services?

**Comment by jdesboeufs** [comment]
Hi,

With the current preloaded dataset, redis will take ~5GB and addok between 400MB and 1GB, depending on pending geocoding requests.

**Comment by jdesboeufs** [comment]
`docker stats` on a random node of our production cluster.

<img width="689" alt="Capture d’écran 2020-02-26 à 14 13 02" src="https://user-images.githubusercontent.com/1231232/75347917-1ba58500-58a2-11ea-9d96-cd50e557b829.png">

**Comment by kopax** [comment]
Excellent and thanks !
