### ISSUE TITLE
Sécurité des images docker hub : "etalab/addok" & "etalab/addok-redis"

### ISSUE THREAD

**Issue by mferuglio** [etalab/addok-docker#31]
Bonjour,

J'ai pull les images docker du fichier [docker-compose](https://raw.githubusercontent.com/BaseAdresseNationale/addok-docker/master/docker-compose.yml) d'exemple du projet.

Après une rapide analyse de sécurité, je me suis dit que je devais vous communiquer les résultats : 
- image "[etalab/addok](https://hub.docker.com/r/etalab/addok)" > **1782 vulnérabilités dont 27 critiques**
- image "[etalab/addok-redis](https://hub.docker.com/r/etalab/addok-redis)" > 107 vulnérabilité donc 2 critiques 

![image](https://github.com/BaseAdresseNationale/addok-docker/assets/79925551/df2f1794-313f-4c11-a13a-2cd5764390cd)
![image](https://github.com/BaseAdresseNationale/addok-docker/assets/79925551/7f298711-d711-4a8c-ab41-b234134db85d)

Amicalement,

**Comment by jdesboeufs** [comment]
Ces images sont obsolètes

**Comment by mferuglio** [comment]
Bonjour @jdesboeufs 

Auriez-vous la possibilité de mettre à jour ces images docker plus souvent ?

Vous devez certainement utiliser un système de CI CD dans votre équipe.
Si oui, il doit vous être possible de pousser en automatique chaque realese de prod sur docker hub (ce serait vraiment cool pour la commu).

D'autant plus que ces images sont quand même "fortement" utilisées :

![image](https://github.com/BaseAdresseNationale/addok-docker/assets/79925551/633fb26c-035e-499a-b387-2f9722648e09)

Par avance,
Merci

**Comment by jdesboeufs** [comment]
Nous n'utilisons plus docker en prod sur l'API Adresse.
Pour ma part je ne suis plus en charge du dossier à la DINUM et j'utilise d'autres images.

**Comment by KGALLET** [comment]
@jdesboeufs Je viens de tomber sur ce thread, il semblerait que vous étiez les des principal contributeur au projet.
Avez-vous des précos sur les images à utiliser ? 
Merci

**Comment by jdesboeufs** [comment]
Bonjour,

En effet ce fut le cas pendant quelques années !
Maintenant cela se passe surtout du côté de https://github.com/livingdata-co/addok-server :)

**Comment by KGALLET** [comment]
Bonjour,

Merci pour votre réponse,
J'ai en effet vu ce repo hier soir et commencé à regarder comment c'était fait! 
Merci bien
