### ISSUE TITLE
Donnée absente sur la version standalone vs api officielle (export addok quasiment vide : 116Mo vs 1Go)

### ISSUE THREAD

**Issue by JulienThilliezLM2** [etalab/addok-docker#36]
Bonjour,

J'ai des différences de résultat entre la version standalone et l'api officielle, par exemple : 

https://api-adresse.data.gouv.fr/search/?q=94%20Rue%20de%20Claye%2077400%20Thorigny-sur-Marne 
retourne bien un résultat, alors que la version standalone ne le retourne pas. La recherche est : "94 Rue de Claye 77400 Thorigny-sur-Marne".

Je viens de faire le test a l'instant avec une image + conteneur neuf, et j'ai le même résultat. 

Dans le cadre d'un autre système, nous intégrons le fichier addock tous les jours dans une base postgres, et je trouve des references a cette adresse  en date du 19/09/2024. En vérifiant ce matin, je ne retrouve pas cet UUID dans l'export addok https://adresse.data.gouv.fr/data/ban/adresses/latest/addok/adresses-addok-france.ndjson.gz

Avez vous une idée de ce qui pourrait générer cette différence de contenu entre les deux apis ? 

Merci par avance et bonne journée ! 

Note, j'ai pas mal de cas concernés, voici quelques exemples (je vais les alimenter au fil de l'eau):
```
56 boulevard de Valmy 92700 COLOMBES
1 rue du cornillon 38120 FONTANIL CORNILLON, France
129 AVENUE DE FRANCE 75013 PARIS 13   ## Celui la ne retourne que des streets, alors que l'api officielle a bien le housenumber
19 RUE KLEBER 85200 FONTENAY LE COMTE
```

**Comment by JulienThilliezLM2** [comment]
Je viens de trouver, l'archive addok exportée a l'air d'être corrompue.

Une ancienne archive du 28/08/2024 pesait 1Go, celle en cours (https://adresse.data.gouv.fr/data/ban/adresses/latest/addok/adresses-addok-france.ndjson.gz) ne pèse que 116Mo et la validation du zip est en erreur : 

gzip: adresses-addok-france.ndjson (1).gz: invalid compressed data--crc error
gzip: adresses-addok-france.ndjson (1).gz: invalid compressed data--length error

**Comment by JulienThilliezLM2** [comment]
Pour info (pour les gens également touchés par le pb), j'ai eu hier la confirmation du pb par mail de l'équipe concernée, ils sont sur le coup, et ce matin le dump est de nouveau d'un 1go (mais pas de mail de la ban pour donner le "Go")

**Comment by coloco21** [comment]
J'ai le même souci, pourtant j'ai mis en place mon instance Addok cette après-midi. Exemple avec l'adresse "29 boulevard de Champigny 94210 LA VARENNE ST HILAIRE" : 2 résultats via l'API officielle et aucun via mon serveur Addok.

**Comment by JulienThilliezLM2** [comment]
Réponse de leur support hier : 

```
Nous avons détecté un problème de données sur le département 24, qui avait bloqué la génération des exports --> exports incomplets.
Les fichiers "latest" ont été rétablis à partir du 26/10
Les fichiers "weekly" du 25/09 sont incomplets, ceux du 02/10 sont bons (générés le mercredi).
```

Je ferme l'issue.
