### ISSUE TITLE
Jeux de données par code INSEE

### ISSUE THREAD

**Issue by oliv3** [etalab/addok-docker#5]
Bonjour, cette version docker me serait très utile pour porter un projet à destination de CT.
Étant un peu limité en RAM, est-il envisagé/envisageable de fournir des parties de la base (par exemple, selon le code INSEE d'une commune) ? Merci !

**Comment by 2ec0b4** [comment]
Tu as un exemple ici : https://addok.readthedocs.io/en/latest/import/

`sed -n 's/"Île-de-France"/&/p' path/to/full.sjson > idf.sjson`

Tu devrais pouvoir faire la même chose avec un code INSEE particulier

**Comment by oliv3** [comment]
Merci pour le lien !
